apiVersion: apps/v1
kind: Deployment
metadata:
  name: flux
  namespace: flux-system
spec:
  template:
    spec:
      nodeSelector:
        node-role.kubernetes.io/control-plane: "true"
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"

      