---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: prometheus
  namespace: flux-system
spec:
  interval: 24h
  url: https://prometheus-community.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: flux-system
spec:
  interval: 24h
  chart:
    spec:
      chart: kube-prometheus-stack
      version: '55.8.3'
      sourceRef:
        kind: HelmRepository
        name: prometheus
  values:
    alertmanager:
      alertmanagerSpec:
        nodeSelector:
          node-role.kubernetes.io/control-plane: "true"
        tolerations:
          - key: "node-role.kubernetes.io/control-plane"
            operator: "Equal"
            value: "true"
            effect: "NoSchedule"

    grafana:
      ingress:
        enabled: true
      nodeSelector:
        node-role.kubernetes.io/control-plane: "true"
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"

    kube-state-metrics:
      nodeSelector:
        node-role.kubernetes.io/control-plane: "true"
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"

    prometheus:
      prometheusSpec:
        nodeSelector:
          node-role.kubernetes.io/control-plane: "true"
        tolerations:
          - key: "node-role.kubernetes.io/control-plane"
            operator: "Equal"
            value: "true"
            effect: "NoSchedule"
        serviceMonitorSelectorNilUsesHelmValues: false

    prometheusOperator:
      admissionWebhooks:
        patch:
          nodeSelector:
            node-role.kubernetes.io/control-plane: "true"
          tolerations:
            - key: "node-role.kubernetes.io/control-plane"
              operator: "Equal"
              value: "true"
              effect: "NoSchedule"

        deployment:
          nodeSelector:
            node-role.kubernetes.io/control-plane: "true"
          tolerations:
            - key: "node-role.kubernetes.io/control-plane"
              operator: "Equal"
              value: "true"
              effect: "NoSchedule"

      nodeSelector:
        node-role.kubernetes.io/control-plane: "true"
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"

  targetNamespace: monitoring
