name: Benchmark Pipeline Test

on: [pull_request, push]

jobs:
  integration-test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Flux CLI
        uses: fluxcd/flux2/action@main
      - name: Setup Kubernetes Kind
        uses: helm/kind-action@main
      - name: Install kepler
        run: |
          flux bootstrap github \
            --owner=${{ github.repository_owner }} \
            --repository=${{ github.repository }} \
            --branch=${{ github.ref_name }} \
            --path=./clusters \
            --personal \
            --token=${{ secrets.GITHUB_TOKEN }} \
            --readonly

          sleep 20

          kubectl wait pod \
          --all \
          --for=condition=Ready \
          --namespace kepler
