name: Benchmark Pipeline Test

on: [push]

jobs:
  integration-test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Flux CLI
        uses: fluxcd/flux2/action@main
      - name: Setup Kubernetes Kind
        uses: helm/kind-action@main
        with:
          config: hack/kind-config.yaml
      - name: Install Flux in Kubernetes Kind
        run: flux install
      - name: Install kubectl
        uses: azure/setup-kubectl@v4
      - name: Install kepler
        run: |
          kubectl apply -f clusters/base/monitoring-namespace.yaml
          kubectl apply -f clusters/base/

          sleep 20

          kubectl get helmrelease -A
          kubectl get pods -A
          
          kubectl wait pod \
          --all \
          --for=condition=Ready \
          --namespace monitoring
          
          kubectl get helmrelease -A
          kubectl get pods -A

          flux reconcile helmrelease -n flux-system kepler
         
          sleep 20

          kubectl wait pod \
          --all \
          --for=condition=Ready \
          --namespace kepler
