name: Benchmark Pipeline Test

on: [push]

jobs:
  setup_kind_cluster:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup Flux CLI
        uses: fluxcd/flux2/action@main
      - name: Setup Kind cluster
        uses: helm/kind-action@main
        with:
          config: hack/kind-config.yaml
      - run: flux install
      - uses: azure/setup-kubectl@v4
      - name: Bootstrap cluster
        run: |
          kubectl apply -f clusters/base/monitoring-namespace.yaml
          kubectl apply -f clusters/base/

          sleep 20

          flux reconcile helmrelease -n flux-system kepler

          kubectl wait pod \
          --all \
          --for=condition=Ready \
          --namespace monitoring
      - name: Generate kubeconfig
        run: |
          ./scripts/gen-kubeconfig.sh pipeline
          ls -l
     - name: Trigger pipeline
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}/actions/workflows/benchmark-pipeline.yaml/dispatches \
          -d '{"event_type": "trigger-pipeline","inputs":{"cncf_project":"falco"}'
